config/routes.rb
Rails.application.routes.draw do




  #main page
  root 'static_pages#home'

  #get 'static_pages/about'
  #get 'static_pages/home'
  #get 'static_pages/help'
  #get 'static_pages/contact'

  get 'about', to: 'static_pages#about'
  get 'help', to: 'static_pages#help'
  get 'contact', to: 'static_pages#contact'

  #signup page

  #get 'users/new' to: '/signup'
  #wrong way, had it backwards

  get 'signup', to: 'users#new' # correct way
  post 'signup', to: 'users#create'

  #adds a full restful url
  resources :users

  #login page
  get '/login', to:'sessions#new'
  post '/login', to:'sessions#create'
  delete '/logout', to: 'sessions#destroy'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord

  attr_accessor :remember_token

  #callback
  #before being saved to the database,fix for case sensivity
  before_save {self.email = email.downcase}

  #constant
  #allows invalid addresses that contain consecutive dots
  #pls fix
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :name, presence: true, length: {maximum: 50}

    #checks if the given email format matches the regex
  validates :email, presence: true, length: {maximum: 255},
            format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }

  #will save a secure hashed password to db
  #will have validations + password confirmation
  #will authenticate when password is correct
  #provided by bcrypt http://en.wikipedia.org/wiki/Bcrypt
  has_secure_password
  validates :password, presence: true, length: {minimum: 6}

  #class method
  #part 1 of a fake user fixture for use in tests
  #digest is a hased password
  #takes a string to turn into a secure password
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def User.new_token
    SecureRandom.urlsafe_base64
  end

  #using self so a local variable isnt created
  #set attribute to generated token
  #set db record to the hash of the token
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  #take the generated token
  #match to the stored hash of that token
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    #user is logging in
    #search for a user by email used to login
    #using params hash containing the session email
    user = User.find_by(email: params[:session][:email].downcase)
    #check if the password matches
    if user && user.authenticate(params[:session][:password])
      #login the user
      #redirect to the users page
      #user_url(user) wwww.test.com/user/id
      log_in user
      remember user #start creating the cookie
      redirect_to user
    else
      #error message
      flash.now[:danger] = "Invalid Email/Password Combo"
      render 'new'
    end
  end


  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    #renders a view even when empty/inherited behavior
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end


  #uses a find by id parameter on the User model
  #to pull the user from the db
  def show
    @user = User.find(params[:id])
    #debugger
  end

  #defining the create action from the user resource
  def create
      @user = User.new(user_params)
      if @user.save
        log_in @user #calls login method
        flash[:success] = "Welcome to our App!"
        redirect_to @user
      else
        render 'new'
      end
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper

 #displays full page title if none is provided
 def full_title(page_title = "")
   base_title = "Ruby on Rails Sample App"
   if page_title.empty?
     base_title
   else
     page_title + " | " + base_title
   end
 end
end

app/helpers/sessions_helper.rb
module SessionsHelper


  def log_in(user)
    session[:user_id] = user.id
  end

  #allows us to check for the current user
  #changes can be made based on the results
  def current_user
    if  (user_id = session[:user_id])
      @current_user || User.find_by(id: session[:user_id])
    elsif (user_id = cookies[:user_id])
      user = User.find_by(id: cookies.signed[:user_id])
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current = user
      end
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end

  #creates a permanent + signed cookie based on the user id
  #creates a cookie to store the generated token
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  #removes cookies on logout
  def forget(user)
    user.forget # updates diget to nil
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end




end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  #assings a gravatar id based on the md5 hash of the users email
  #url is based on users email they signup with
  #will return the default if none is provided
  def gravatar_for(user, size: 100)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The
    <a href="http://www.railstutorial.org/">
        Ruby on Rails Tutorial
    </a>
    by
    <a href="http://www.michaelhartl.com/">
      Michael Hartl
    </a>
  </small>

  <nav>
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li>
        <a href="http://www.news.google.com">
          News
        </a>
      </li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "sample app", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Help", help_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Users", '#' %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Settings", '#' %></li>
              <li><%= link_to "Profile", current_user %></li>
              <li class="divider"></li>
              <li><%= link_to "Log Out", logout_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <%end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= render "layouts/rails_default" %>
  </head>

  <body>
  <%= render "layouts/header" %>
    <div class="container">
      <%flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>">
          <%=message%>
        </div>
      <%end%>
      <%= yield %>

      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
        <li>
          <%= msg %>
        </li>
    <% end %>
    </ul>
  </div>
<% end%>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>

    <h1>About</h1>
    <p>
      This a sample ruby on rails application. It demonstrates static pages and TDD.
    </p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  Contact the Ruby on Rails Tutorial about the sample app at the
  <a href="http://www.railstutorial.org/contact">contact page</a>.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>

    <h1>Help</h1>
    <p>
      This a sample ruby on rails application. It demonstrates static pages and TDD.
    </p>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>Welcome to the app.</h1>
    <h2> This is the home page for the
      <a href="http://www.railstutorial.org/">
        Ruby on Rails Tutorial
      </a>sample application.
    </h2>

    <%= link_to 'Sign me up!', signup_path, class: "btn btn-lg btn-primary" %>
</div>

<%= link_to image_tag('rails.png', alt: "Rails logo"), 'http://www.rubyonrails.org' %>

app/views/users/new.html.erb
<% provide(:title, 'Sign Up') %>
<h1>Sign Up!</h1>

<div class="row">
  <div class="col-md-6 cold-md-offset-3">
    <%= form_for(@user, url: signup_path) do |f| %>
      <%= render 'shared/error_messages' %>

      <%=f.label :name %>
      <%=f.text_field :name, class: "form-control" %>

      <%=f.label :email %>
      <%=f.email_field :email, class: "form-control" %>

      <%=f.label :password %>
      <%=f.password_field :password, class: "form-control" %>

      <%=f.label :password_confirmation, "Pass Confirmation"%>
      <%=f.password_field :password_confirmation, class: "form-control" %>

      <%=f.submit "Create Account", class: "btn btn-primary" %>
    <% end %>
    <p>Already have an account? <%= link_to "Login Now", login_path%></p>
  </div>
</div>

app/views/users/show.html.erb
<%= provide(:title, @user.name) %>

<!--displays the users name + email using an instance variable -->
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>


<ul>
  <li>Email: <%= @user.email %></li>
  <li>Created: <%= @user.created_at %></li>
  <li>Updated: <%= @user.updated_at %></li>
  <li>Current Time: <%= Time.now %> </li>
</ul>